# -*- coding: utf-8 -*-
"""TSG JEPA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IhrO8vOARmcf-ImWpPcjB9zuaJMEY6H0
"""

# =============================================================
# CELL 1 — Install dependencies and mount Drive
# =============================================================
!pip install -q torchvision pillow tqdm scikit-learn h5py wilds datasets

from google.colab import drive
drive.mount('/content/drive')

# =============================================================
# CELL 2 — Imports, utilities, and CFG dataclass
# =============================================================
from __future__ import annotations
import copy, json, math, random, time, os, gc
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import List, Tuple, Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.transforms import functional as TF
from tqdm.auto import tqdm

from sklearn.metrics import (roc_auc_score, roc_curve, f1_score,
                              precision_score, recall_score,
                              confusion_matrix as sk_cm)
import matplotlib.pyplot as plt


def set_seed(s=456):
    random.seed(s); np.random.seed(s)
    torch.manual_seed(s); torch.cuda.manual_seed_all(s)
    torch.backends.cudnn.benchmark = True
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    torch.set_float32_matmul_precision('high')


def gn(ch, g=8):
    while g > 1 and ch % g:
        g //= 2
    return nn.GroupNorm(g, ch)


def cos_sched(base, final, step, total, warmup=0):
    if step < warmup:
        return base * (step + 1) / max(1, warmup)
    p = min(max((step - warmup) / max(1, total - warmup), 0.0), 1.0)
    return final + 0.5 * (base - final) * (1.0 + math.cos(math.pi * p))


def two_stage_ema(step, total, fast=0.99, slow=0.9995, switch=0.30):
    sw = int(total * switch)
    if step < sw:
        return fast
    p = min(max((step - sw) / max(1, total - sw), 0.0), 1.0)
    return fast + 0.5 * (slow - fast) * (1.0 + math.cos(math.pi * (1.0 - p)))


@dataclass
class CFG:
    img_size: int = 96
    local_size: int = 64
    n_local: int = 2
    in_ch: int = 3
    num_classes: int = 2
    batch_size: int = 192
    eval_bs: int = 384
    num_workers: int = 4

    seed: int = 789
    ssl_epochs: int = 40
    ft_epochs: int = 20
    probe_epochs: int = 15
    warmup_epochs: int = 4
    lr: float = 5e-4
    ft_lr: float = 3e-4
    probe_lr: float = 1e-3
    wd: float = 2e-2
    grad_clip: float = 1.0
    use_amp: bool = True

    width: int = 160
    depth: int = 3
    latent: int = 512
    mlp_ratio: float = 2.0
    block_drop: float = 0.05
    drop_path: float = 0.10
    se_ratio: float = 0.25
    head_drop: float = 0.30
    label_smooth: float = 0.05
    conv_groups_div: int = 6
    gamma_init: float = 0.1

    spike_steps: int = 1
    vth: float = 0.5
    tau: float = 2.0
    gate_floor: float = 0.50
    gate_beta_init: float = 5.0

    mask_ratio: float = 0.55
    min_blk: int = 4
    max_blk: int = 10
    pred_depth: int = 2
    ema_fast: float = 0.99
    ema_slow: float = 0.9995
    ema_switch_frac: float = 0.30

    lam_spatial: float = 1.0
    lam_var: float = 0.3
    lam_local: float = 0.5
    target_fr: float = 0.10
    lam_fr: float = 0.05

    finetune_freeze_epochs: int = 1
    ft_patience: int = 10
    ssl_patience: int = 8
    eval_every: int = 4
    tta: bool = True
    focal_gamma: float = 1.5

    lam_equiv: float = 0.3
    equiv_warmup_epochs: int = 2
    equiv_prob: float = 0.5
    use_sam: bool = True
    sam_rho: float = 0.05
    sam_start_epoch: int = 4
    use_anchors: bool = True
    lam_anchor: float = 0.2
    anchor_margin: float = 0.3

    model_ema_decay: float = 0.9995
    model_ema_warmup: int = 2

    pad_mode: str = "circular"
    toroidal_blend_init: float = 2.2

    dataset_name: str = "camelyon17"
    wilds_root: str = "/content/wilds_data"
    select_on_ood: bool = True
    stain_jitter_strength: float = 1.5

    data_root: str = "/content/wilds_data"

    # IMPORTANT: separate Drive folder for Seed 456
    out_dir: str = "/content/drive/MyDrive/camelyon17_v1/tsj_seed789"


cfg = CFG()
set_seed(cfg.seed)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

for p in [cfg.data_root, cfg.out_dir]:
    Path(p).mkdir(parents=True, exist_ok=True)

print(f"{device} | width={cfg.width} depth={cfg.depth} latent={cfg.latent}")
print(f"Dataset: CAMELYON17-WILDS | OOD selection: {cfg.select_on_ood}")

# Save the exact settings alongside this seed's metrics and checkpoints.
with open(Path(cfg.out_dir) / "run_config.json", "w") as f:
    json.dump(asdict(cfg), f, indent=2)

print(f"Seed: {cfg.seed} | SSL epoch limit: {cfg.ssl_epochs} | FT epoch limit: {cfg.ft_epochs}")
print(f"Saving this run to: {cfg.out_dir}")

# =============================================================
# CELL 3 — CAMELYON17-WILDS via HuggingFace mirror
# =============================================================
import os, shutil, re
from pathlib import Path
from datasets import load_dataset
import pandas as pd

WILDS_ROOT = "/content/wilds_data"
DATA_DIR = f"{WILDS_ROOT}/camelyon17_v1.0"
PATCHES_DIR = f"{DATA_DIR}/patches"
METADATA = f"{DATA_DIR}/metadata.csv"
RELEASE_MARKER = f"{DATA_DIR}/RELEASE_v1.0.txt"

os.makedirs(PATCHES_DIR, exist_ok=True)

if not os.path.exists(METADATA):
    print("Downloading CAMELYON17-WILDS from HuggingFace mirror (~10GB)...")
    hf = load_dataset("wltjr1007/Camelyon17-WILDS", cache_dir="/content/hf_cache")
    split_map = {"train": 0, "validation": 1, "test": 2}
    rows = []
    for hf_split, wilds_split_code in split_map.items():
        print(f"  Processing {hf_split} ({len(hf[hf_split]):,} samples)...")
        for i, item in enumerate(tqdm(hf[hf_split])):
            patient = int(item["patient"])
            node = int(item["node"])
            x = int(item["x_coord"])
            y = int(item["y_coord"])
            label = int(item["label"])
            slide = int(item["slide"])
            center = int(item["center"])
            folder = f"{PATCHES_DIR}/patient_{patient}_node_{node}"
            os.makedirs(folder, exist_ok=True)
            fname = f"patch_patient_{patient}_node_{node}_x_{x}_y_{y}.png"
            fpath = f"{folder}/{fname}"
            if not os.path.exists(fpath):
                item["image"].save(fpath)
            rows.append({
                "patient": patient, "node": node,
                "x_coord": x, "y_coord": y,
                "tumor": label, "slide": slide,
                "center": center, "split": wilds_split_code,
            })
    print("Writing metadata.csv...")
    df = pd.DataFrame(rows)
    df.to_csv(METADATA, index=True)
    shutil.rmtree("/content/hf_cache", ignore_errors=True)

# Ensure WILDS marker exists
if not os.path.exists(RELEASE_MARKER):
    Path(RELEASE_MARKER).touch()

print(f"✓ Data ready at {DATA_DIR}")

from wilds import get_dataset

MU = (0.701, 0.538, 0.692)
SIG = (0.235, 0.277, 0.213)
CLASSES = ["normal", "tumour"]


class RandomRot90:
    def __call__(self, img):
        k = random.randint(0, 3)
        return img if k == 0 else TF.rotate(img, k * 90)


class GaussianNoise:
    def __init__(self, std=0.015, p=0.2):
        self.std, self.p = std, p
    def __call__(self, x):
        if random.random() > self.p:
            return x
        return (x + torch.randn_like(x) * self.std).clamp(0.0, 1.0)


class StainJitter:
    def __init__(self, sm=0.15, sa=0.05, p=0.6):
        self.sm, self.sa, self.p = sm, sa, p
    def __call__(self, x):
        if random.random() > self.p:
            return x
        mul = 1.0 + torch.randn(3, 1, 1, device=x.device) * self.sm
        add = torch.randn(3, 1, 1, device=x.device) * self.sa
        return (x * mul + add).clamp(0.0, 1.0)


def _build_tf(crop_size, scale, jitter_p=0.8, stain=(0.18, 0.07, 0.7),
              noise=(0.015, 0.20), erase=False):
    s = cfg.stain_jitter_strength
    stain_boosted = (stain[0] * s, stain[1] * s, stain[2])
    ops = [
        transforms.RandomResizedCrop(crop_size, scale=scale, interpolation=Image.BICUBIC),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        RandomRot90(),
        transforms.RandomApply([transforms.ColorJitter(0.50, 0.50, 0.30, 0.08)], p=jitter_p),
        transforms.ToTensor(),
        StainJitter(*stain_boosted),
        GaussianNoise(*noise),
        transforms.Normalize(MU, SIG),
    ]
    if erase:
        ops.append(transforms.RandomErasing(p=0.25, scale=(0.02, 0.15), ratio=(0.3, 3.3)))
    return transforms.Compose(ops)


ctx_global_tf = _build_tf(cfg.img_size, (0.55, 1.0))
tgt_global_tf = transforms.Compose([
    transforms.RandomResizedCrop(cfg.img_size, scale=(0.70, 1.0), interpolation=Image.BICUBIC),
    transforms.RandomHorizontalFlip(), transforms.RandomVerticalFlip(), RandomRot90(),
    transforms.ToTensor(),
    StainJitter(0.12 * cfg.stain_jitter_strength, 0.05 * cfg.stain_jitter_strength, 0.5),
    transforms.Normalize(MU, SIG),
])
local_tf = _build_tf(cfg.local_size, (0.40, 0.70), jitter_p=0.8,
                      stain=(0.15, 0.06, 0.6), noise=(0.0, 0.0))
ft_tf = _build_tf(cfg.img_size, (0.95, 1.0), jitter_p=0.7,
                   stain=(0.15, 0.06, 0.6), noise=(0.01, 0.15), erase=True)
eval_tf = transforms.Compose([transforms.ToTensor(), transforms.Normalize(MU, SIG)])


print("Loading via WILDS...")
wilds_dataset = get_dataset(dataset="camelyon17", root_dir=WILDS_ROOT, download=False)
print(f"  Total samples: {len(wilds_dataset):,}")


class CamelyonFT(Dataset):
    def __init__(self, wilds_subset, transform=None):
        self.subset = wilds_subset
        self.transform = transform
    def __len__(self):
        return len(self.subset)
    def __getitem__(self, i):
        x, y, _ = self.subset[i]
        if not isinstance(x, Image.Image):
            x = transforms.ToPILImage()(x)
        x = x.convert("RGB")
        if self.transform is not None:
            x = self.transform(x)
        return x, int(y)


class CamelyonSSL(Dataset):
    def __init__(self, wilds_subset, ctx_tf, tgt_tf, local_tf, n_local):
        self.subset = wilds_subset
        self.ctx_tf, self.tgt_tf, self.local_tf = ctx_tf, tgt_tf, local_tf
        self.n_local = n_local
    def __len__(self):
        return len(self.subset)
    def __getitem__(self, i):
        x, _, _ = self.subset[i]
        if not isinstance(x, Image.Image):
            x = transforms.ToPILImage()(x)
        x = x.convert("RGB")
        return (self.ctx_tf(x), self.tgt_tf(x),
                torch.stack([self.local_tf(x) for _ in range(self.n_local)], dim=0))


train_sub = wilds_dataset.get_subset("train")
id_val_sub = wilds_dataset.get_subset("id_val")
ood_val_sub = wilds_dataset.get_subset("val")
ood_test_sub = wilds_dataset.get_subset("test")

ssl_ds = CamelyonSSL(train_sub, ctx_global_tf, tgt_global_tf, local_tf, cfg.n_local)
ft_train_ds = CamelyonFT(train_sub, transform=ft_tf)
ft_train_eval_ds = CamelyonFT(train_sub, transform=eval_tf)
id_val_ds = CamelyonFT(id_val_sub, transform=eval_tf)
ood_val_ds = CamelyonFT(ood_val_sub, transform=eval_tf)
ood_test_ds = CamelyonFT(ood_test_sub, transform=eval_tf)

kw = dict(num_workers=cfg.num_workers, pin_memory=True,
          persistent_workers=(cfg.num_workers > 0))
if cfg.num_workers > 0:
    kw["prefetch_factor"] = 4

ssl_dl = DataLoader(ssl_ds, batch_size=cfg.batch_size, shuffle=True, drop_last=True, **kw)
ft_dl  = DataLoader(ft_train_ds, batch_size=cfg.batch_size, shuffle=True, drop_last=True, **kw)
tr_dl  = DataLoader(ft_train_eval_ds, batch_size=cfg.eval_bs, shuffle=False, **kw)
va_dl  = DataLoader(ood_val_ds if cfg.select_on_ood else id_val_ds,
                    batch_size=cfg.eval_bs, shuffle=False, **kw)
id_va_dl  = DataLoader(id_val_ds, batch_size=cfg.eval_bs, shuffle=False, **kw)
ood_va_dl = DataLoader(ood_val_ds, batch_size=cfg.eval_bs, shuffle=False, **kw)
te_dl  = DataLoader(ood_test_ds, batch_size=cfg.eval_bs, shuffle=False, **kw)

va_ds = ood_val_ds if cfg.select_on_ood else id_val_ds
te_ds = ood_test_ds

print(f"\nSSL train:    {len(ssl_ds):,}")
print(f"FT train:     {len(ft_train_ds):,}")
print(f"ID val:       {len(id_val_ds):,}")
print(f"OOD val:      {len(ood_val_ds):,}")
print(f"OOD test:     {len(ood_test_ds):,}")
print("✅ Cell 3 ready")

# =============================================================
# CELL 4 — Spiking primitives (FIXED: fr only updates in train)
# =============================================================
class SpikeGateV2(nn.Module):
    def __init__(self, ch, tau=2.0, vth=0.5, steps=1, floor=0.5, beta_init=5.0):
        super().__init__()
        self.norm = gn(ch)
        self.vth = nn.Parameter(torch.full((1, ch, 1, 1), vth))
        self.beta = nn.Parameter(torch.tensor(beta_init))
        self.floor = floor
        self.fr = None

    def forward(self, x):
        sp = torch.sigmoid(self.beta * (self.norm(x) - self.vth))
        if self.training:
            self.fr = sp.detach().mean()
        return x * (self.floor + (1.0 - self.floor) * sp)


class DropPath(nn.Module):
    def __init__(self, p=0.0):
        super().__init__()
        self.p = float(p)

    def forward(self, x):
        if self.p == 0.0 or not self.training:
            return x
        keep = 1.0 - self.p
        mask = x.new_empty((x.shape[0],) + (1,) * (x.ndim - 1)).bernoulli_(keep)
        return x * mask / keep


class SqueezeExcite(nn.Module):
    def __init__(self, ch, rd=0.25):
        super().__init__()
        hid = max(8, int(ch * rd))
        self.net = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(ch, hid, 1), nn.GELU(),
            nn.Conv2d(hid, ch, 1), nn.Sigmoid())

    def forward(self, x):
        return x * self.net(x)

print("Cell 4 ready")

# =============================================================
# CELL 5 — Architecture
# =============================================================
class TConvHybrid(nn.Module):
    def __init__(self, ci, co, k=3, s=1, g=1, blend_init=2.2):
        super().__init__()
        p = k // 2
        self.conv_circ = nn.Conv2d(ci, co, k, s, p, groups=g, padding_mode="circular", bias=False)
        self.conv_ref = nn.Conv2d(ci, co, k, s, p, groups=g, padding_mode="reflect", bias=False)
        nn.init.kaiming_normal_(self.conv_circ.weight, nonlinearity="relu")
        with torch.no_grad():
            self.conv_ref.weight.copy_(self.conv_circ.weight)
        self.alpha = nn.Parameter(torch.tensor(blend_init))

    def forward(self, x):
        a = torch.sigmoid(self.alpha)
        return a * self.conv_circ(x) + (1 - a) * self.conv_ref(x)


class TConvPure(nn.Module):
    def __init__(self, ci, co, k=3, s=1, g=1):
        super().__init__()
        self.conv = nn.Conv2d(ci, co, k, s, k // 2, groups=g, padding_mode="circular", bias=False)
        nn.init.kaiming_normal_(self.conv.weight, nonlinearity="relu")

    def forward(self, x):
        return self.conv(x)


class Stem(nn.Module):
    def __init__(self, c):
        super().__init__()
        w = c.width
        sk = dict(tau=c.tau, vth=c.vth, steps=c.spike_steps,
                  floor=c.gate_floor, beta_init=c.gate_beta_init)
        self.layers = nn.Sequential(
            TConvHybrid(c.in_ch, w // 4, 3, 2, blend_init=c.toroidal_blend_init),
            gn(w // 4), nn.GELU(), SpikeGateV2(w // 4, **sk),
            TConvHybrid(w // 4, w // 2, 3, 2, blend_init=c.toroidal_blend_init),
            gn(w // 2), nn.GELU(), SpikeGateV2(w // 2, **sk),
            TConvHybrid(w // 2, w, 3, 1, blend_init=c.toroidal_blend_init),
            gn(w), nn.GELU(), SpikeGateV2(w, **sk),
        )

    def forward(self, x):
        return self.layers(x)


class BottleneckBlock(nn.Module):
    def __init__(self, ch, hid, c, dp_p=0.0):
        super().__init__()
        sk = dict(tau=c.tau, vth=c.vth, steps=c.spike_steps,
                  floor=c.gate_floor, beta_init=c.gate_beta_init)
        groups = max(1, hid // c.conv_groups_div)
        while groups > 1 and hid % groups != 0:
            groups -= 1
        self.conv1 = nn.Conv2d(ch, hid, 1, bias=False)
        self.norm1 = gn(hid)
        self.gate1 = SpikeGateV2(hid, **sk)
        self.conv2 = TConvHybrid(hid, hid, 3, 1, g=groups, blend_init=c.toroidal_blend_init)
        self.norm2 = gn(hid)
        self.gate2 = SpikeGateV2(hid, **sk)
        self.se = SqueezeExcite(hid, c.se_ratio)
        self.drop = nn.Dropout2d(c.block_drop)
        self.conv3 = nn.Conv2d(hid, ch, 1, bias=False)
        self.norm3 = gn(ch)
        self.gamma = nn.Parameter(torch.ones(1, ch, 1, 1) * c.gamma_init)
        self.dp = DropPath(dp_p)

    def forward(self, x, mask=None):
        r = x
        x = self.gate1(F.gelu(self.norm1(self.conv1(x))))
        x = self.gate2(F.gelu(self.norm2(self.conv2(x))))
        x = self.drop(self.se(x))
        x = self.dp(self.gamma * self.norm3(self.conv3(x)))
        out = F.gelu(r + x)
        if mask is not None and mask.shape[-2:] == out.shape[-2:]:
            out = out * (1.0 - mask)
        return out


class Encoder(nn.Module):
    def __init__(self, c):
        super().__init__()
        w = c.width
        h = int(c.width * c.mlp_ratio)
        self.stem = Stem(c)
        dp_rates = [c.drop_path * i / max(1, c.depth - 1) for i in range(c.depth)] if c.depth > 1 else [0.0]
        self.blocks = nn.ModuleList([BottleneckBlock(w, h, c, dp_p=dp_rates[i]) for i in range(c.depth)])
        self.head = nn.Sequential(nn.Conv2d(w, w, 1, bias=False), gn(w),
                                   nn.GELU(), nn.Dropout2d(c.block_drop))
        self.proj = nn.Sequential(nn.Linear(w * 3, c.latent), nn.LayerNorm(c.latent))

    def features(self, x, mask=None):
        x = self.stem(x)
        if mask is not None and mask.shape[-2:] == x.shape[-2:]:
            x = x * (1.0 - mask)
        for blk in self.blocks:
            x = blk(x, mask)
        return self.head(x)

    def multi_scale_pool(self, fmap):
        z_mean = fmap.mean(dim=[2, 3])
        z_max = fmap.amax(dim=[2, 3])
        scores = fmap.norm(dim=1, keepdim=True)
        weights = F.softmax(scores.flatten(2), dim=-1)
        z_attn = (fmap.flatten(2) * weights).sum(-1)
        return torch.cat([z_mean, z_max, z_attn], dim=1)

    def pooled(self, fmap):
        return self.proj(self.multi_scale_pool(fmap))

    def forward(self, x, mask=None):
        fmap = self.features(x, mask)
        return fmap, self.pooled(fmap)

    def spike_stats(self):
        rates = [m.fr for m in self.modules() if isinstance(m, SpikeGateV2) and m.fr is not None]
        if not rates:
            return torch.tensor(0.0, device=next(self.parameters()).device)
        return torch.stack(rates).mean()


class Masker:
    def __init__(self, ratio, mn, mx, fmap_h=24, fmap_w=24, cache=2048):
        target = int(round(fmap_h * fmap_w * ratio))
        masks = torch.zeros(cache, 1, fmap_h, fmap_w)
        for i in range(cache):
            m = masks[i, 0]
            while m.sum() < target:
                bh, bw = random.randint(mn, mx), random.randint(mn, mx)
                top, left = random.randint(0, fmap_h - 1), random.randint(0, fmap_w - 1)
                rows = (torch.arange(bh) + top) % fmap_h
                cols = (torch.arange(bw) + left) % fmap_w
                m[rows[:, None], cols[None, :]] = 1.0
        self.masks = masks
        self.cache = cache

    def __call__(self, B, dev):
        idx = torch.randint(0, self.cache, (B,))
        return self.masks[idx].to(device=dev, non_blocking=True)


FMAP_H = cfg.img_size // 4
FMAP_W = cfg.img_size // 4
print("Cell 5 ready")

# =============================================================
# CELL 6 — TSJEPA model + SSL losses
# =============================================================
class SpatialPredictor(nn.Module):
    def __init__(self, ch, depth, drop=0.1):
        super().__init__()
        neck = max(ch // 2, 64)
        layers = [nn.Conv2d(ch, neck, 1, bias=False), gn(neck), nn.GELU()]
        for _ in range(depth - 1):
            layers += [TConvPure(neck, neck, 3, 1, g=neck), gn(neck),
                       nn.GELU(), nn.Dropout2d(drop)]
        layers.append(nn.Conv2d(neck, ch, 1, bias=False))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


class SSLProjector(nn.Module):
    def __init__(self, latent):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(latent, latent, bias=False),
            nn.BatchNorm1d(latent),
            nn.GELU(),
            nn.Linear(latent, latent, bias=False),
        )

    def forward(self, x):
        return self.net(x)


def spatial_loss(pred, tgt, mask):
    p = F.normalize(pred, dim=1)
    t = F.normalize(tgt.detach(), dim=1)
    err = (1.0 - (p * t).sum(dim=1, keepdim=True)) * mask
    return err.sum() / mask.sum().clamp_min(1)


def vicreg_var_loss(z):
    z = z - z.mean(0, keepdim=True)
    std = (z.var(0) + 1e-4).sqrt()
    return F.relu(1.0 - std).mean()


def local_global_loss(z_local, z_global):
    p = F.normalize(z_local, dim=-1)
    t = F.normalize(z_global.detach(), dim=-1)
    return (1.0 - (p * t).sum(-1)).mean()


class TSJEPA(nn.Module):
    def __init__(self, c):
        super().__init__()
        self.c = c
        self.online = Encoder(c)
        self.target = Encoder(c)
        self.pred = SpatialPredictor(c.width, c.pred_depth, c.block_drop)
        self.ssl_proj_online = SSLProjector(c.latent)
        self.ssl_proj_target = SSLProjector(c.latent)
        self.masker = Masker(c.mask_ratio, c.min_blk, c.max_blk, FMAP_H, FMAP_W)
        self.target.load_state_dict(copy.deepcopy(self.online.state_dict()))
        self.ssl_proj_target.load_state_dict(copy.deepcopy(self.ssl_proj_online.state_dict()))
        for p in self.target.parameters():
            p.requires_grad_(False)
        for p in self.ssl_proj_target.parameters():
            p.requires_grad_(False)
        self.ema_d = c.ema_fast

    @torch.no_grad()
    def ema_step(self, step, total):
        self.ema_d = two_stage_ema(step, total, self.c.ema_fast, self.c.ema_slow, self.c.ema_switch_frac)
        for o, t in zip(self.online.parameters(), self.target.parameters()):
            t.data.mul_(self.ema_d).add_(o.data, alpha=1.0 - self.ema_d)
        for o, t in zip(self.ssl_proj_online.parameters(), self.ssl_proj_target.parameters()):
            t.data.mul_(self.ema_d).add_(o.data, alpha=1.0 - self.ema_d)

    def forward(self, x_ctx, x_tgt, x_locals):
        B = x_ctx.size(0)
        with torch.no_grad():
            tgt_fmap = self.target.features(x_tgt)
            _, z_tgt_raw = self.target(x_tgt)
            z_tgt = self.ssl_proj_target(z_tgt_raw)
        mask = self.masker(B, x_ctx.device)
        ctx_fmap, z_ctx_raw = self.online(x_ctx, mask)
        z_ctx = self.ssl_proj_online(z_ctx_raw)
        l_sp = spatial_loss(self.pred(ctx_fmap), tgt_fmap, mask)

        n = x_locals.size(1)
        x_locals_flat = x_locals.view(B * n, *x_locals.shape[2:])
        _, z_locals_raw = self.online(x_locals_flat)
        z_locals = self.ssl_proj_online(z_locals_raw)
        z_tgt_rep = z_tgt.unsqueeze(1).expand(-1, n, -1).reshape(B * n, -1)
        l_local = local_global_loss(z_locals, z_tgt_rep)

        l_var = vicreg_var_loss(z_ctx)
        fr = self.online.spike_stats()
        l_fr = (fr - self.c.target_fr) ** 2

        total = (self.c.lam_spatial * l_sp + self.c.lam_local * l_local
                 + self.c.lam_var * l_var + self.c.lam_fr * l_fr)
        return total, l_sp, l_local, l_var, fr, mask.mean()


model = TSJEPA(cfg).to(device).to(memory_format=torch.channels_last)
print(f"Online encoder: {sum(p.numel() for p in model.online.parameters())/1e6:.2f}M params")
print(f"SSL projector:  {sum(p.numel() for p in model.ssl_proj_online.parameters())/1e6:.2f}M params (discarded before FT)")

# =============================================================
# CELL 7 — Evaluation (FIXED: raw pooled, mean-vote, stratified, ID+OOD)
# =============================================================
@torch.inference_mode()
def extract(enc, dl):
    enc.eval()
    fs, ys = [], []
    for x, y in dl:
        x = x.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
        fs.append(enc.multi_scale_pool(enc.features(x)).cpu())
        ys.append(y)
    return torch.cat(fs), torch.cat(ys)


@torch.inference_mode()
def knn_eval(trx, try_, tex, tey, k=20):
    trx = F.normalize(trx, dim=-1)
    tex = F.normalize(tex, dim=-1)
    sims = tex @ trx.T
    topk_idx = sims.topk(min(k, trx.size(0)), dim=1).indices
    neighbour_labels = try_[topk_idx]
    pred = (neighbour_labels.float().mean(dim=1) >= 0.5).long()
    return (pred == tey).float().mean().item()


def tta_logits(clf_model, x, strong=False):
    base = []
    for k in range(4):
        xr = torch.rot90(x, k, dims=[2, 3])
        base.append(clf_model(xr))
        base.append(clf_model(torch.flip(xr, dims=[3])))
    if not strong:
        return torch.stack(base, dim=0).mean(0)
    H, W = x.shape[-2:]
    H2, W2 = int(H * 1.1), int(W * 1.1)
    x_zoom = F.interpolate(x, size=(H2, W2), mode='bilinear', align_corners=False)
    top, left = (H2 - H) // 2, (W2 - W) // 2
    x_zoom = x_zoom[..., top:top + H, left:left + W]
    zoom = []
    for k in range(4):
        xr = torch.rot90(x_zoom, k, dims=[2, 3])
        zoom.append(clf_model(xr))
        zoom.append(clf_model(torch.flip(xr, dims=[3])))
    return torch.stack(base + zoom, dim=0).mean(0)


def infer_classifier(clf_model, dl, use_tta=False, strong=False):
    clf_model.eval()
    all_logits, all_true = [], []
    with torch.inference_mode():
        for x, y in dl:
            x = x.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
            lg = tta_logits(clf_model, x, strong=strong) if use_tta else clf_model(x)
            all_logits.append(lg.cpu())
            all_true.append(y)
    logits = torch.cat(all_logits)
    trues = torch.cat(all_true)
    return logits.argmax(1).numpy(), trues.numpy(), torch.softmax(logits, dim=1)[:, 1].numpy()


def report_metrics(preds, trues, probs, label=""):
    acc = (preds == trues).mean()
    auc = roc_auc_score(trues, probs)
    sens = recall_score(trues, preds, pos_label=1)
    spec = recall_score(trues, preds, pos_label=0)
    f1 = f1_score(trues, preds)
    prec = precision_score(trues, preds)
    print(f"\n[{label}] AUC={auc:.4f} Acc={acc:.4f} Sens={sens:.4f} "
          f"Spec={spec:.4f} Prec={prec:.4f} F1={f1:.4f}")


def plot_roc(trues, probs, label=""):
    fpr, tpr, _ = roc_curve(trues, probs)
    auc = roc_auc_score(trues, probs)
    plt.figure(figsize=(5, 5))
    plt.plot(fpr, tpr, lw=2, label=f"AUC={auc:.4f}")
    plt.plot([0, 1], [0, 1], "k--", alpha=0.3)
    plt.xlabel("FPR"); plt.ylabel("TPR"); plt.title(f"ROC {label}")
    plt.legend(); plt.grid(alpha=0.3); plt.tight_layout(); plt.show()


def plot_cm(preds, trues, label=""):
    cm = sk_cm(trues, preds)
    fig, ax = plt.subplots(figsize=(4, 3.5))
    im = ax.imshow(cm, cmap="Blues")
    ax.set_xticks([0, 1]); ax.set_xticklabels(CLASSES)
    ax.set_yticks([0, 1]); ax.set_yticklabels(CLASSES)
    for i in range(2):
        for j in range(2):
            ax.text(j, i, f"{cm[i, j]:,}", ha="center", va="center",
                    color="white" if cm[i, j] > cm.max() / 2 else "black")
    ax.set_xlabel("Pred"); ax.set_ylabel("True"); ax.set_title(f"CM {label}")
    plt.colorbar(im); plt.tight_layout(); plt.show()


def _stratified_subsample(feats, labels, n_per_class=5000, seed=42):
    g = torch.Generator().manual_seed(seed)
    pos_idx = (labels == 1).nonzero(as_tuple=True)[0]
    neg_idx = (labels == 0).nonzero(as_tuple=True)[0]
    n = min(n_per_class, len(pos_idx), len(neg_idx))
    pos_sel = pos_idx[torch.randperm(len(pos_idx), generator=g)[:n]]
    neg_sel = neg_idx[torch.randperm(len(neg_idx), generator=g)[:n]]
    sel = torch.cat([pos_sel, neg_sel])
    return feats[sel], labels[sel]


def ssl_eval(model, ep_label=""):
    full_trx, full_try = extract(model.online, tr_dl)
    full_trx, full_try = _stratified_subsample(full_trx, full_try, n_per_class=5000, seed=42)
    ood_vax, ood_vay = extract(model.online, ood_va_dl)
    knn_ood = knn_eval(full_trx, full_try, ood_vax, ood_vay, k=20)
    id_vax, id_vay = extract(model.online, id_va_dl)
    knn_id = knn_eval(full_trx, full_try, id_vax, id_vay, k=20)
    print(f"  SSL eval {ep_label}: kNN_ID={knn_id:.4f}  kNN_OOD={knn_ood:.4f}")
    return knn_ood, knn_id, None


print("Cell 7 ready")

# =============================================================
# CELL 8 — SSL pretraining loop
# =============================================================
def ssl_train(cfg):
    out = Path(cfg.out_dir)
    opt = torch.optim.AdamW(model.parameters(), lr=cfg.lr, weight_decay=cfg.wd)
    scaler = torch.amp.GradScaler("cuda", enabled=(cfg.use_amp and device.type == "cuda"))

    spe = len(ssl_dl)
    total_steps = cfg.ssl_epochs * spe
    warmup = cfg.warmup_epochs * spe
    step = 0
    best_knn = -1.0
    patience = cfg.ssl_patience
    logs = {k: [] for k in ["epoch", "loss", "spatial", "local", "var", "fr", "ema", "lr", "knn", "knn_id"]}

    resume_path = out / "ssl_resume.pt"
    start_ep = 0
    if resume_path.exists():
        try:
            ckpt = torch.load(resume_path, map_location=device)
            model.online.load_state_dict(ckpt["online"])
            model.target.load_state_dict(ckpt["target"])
            opt.load_state_dict(ckpt["optimizer"])
            scaler.load_state_dict(ckpt["scaler"])
            start_ep = ckpt["epoch"] + 1
            step = ckpt["step"]
            best_knn = ckpt["best_knn"]
            patience = ckpt["patience_left"]
            model.ema_d = ckpt["ema_d"]
            logs_p = out / "ssl_logs.json"
            if logs_p.exists():
                with open(logs_p) as f:
                    logs = json.load(f)
                if "knn_id" not in logs:
                    logs["knn_id"] = []
            print(f"Resumed at epoch {start_ep}, best_knn={best_knn:.4f}")
        except Exception as e:
            print(f"Resume failed: {e}")
            start_ep = 0

    for ep in range(start_ep, cfg.ssl_epochs):
        model.train()
        sums = {k: 0.0 for k in ["loss", "sp", "loc", "var", "fr"]}
        seen = 0
        t0 = time.time()
        pbar = tqdm(ssl_dl, desc=f"SSL {ep+1}/{cfg.ssl_epochs}")
        for batch_i, (x_c, x_t, x_locs) in enumerate(pbar):
            x_c = x_c.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
            x_t = x_t.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
            x_locs = x_locs.to(device, non_blocking=True)
            bs = x_c.size(0)

            lr = cos_sched(cfg.lr, 1e-6, step, total_steps, warmup)
            for g in opt.param_groups:
                g["lr"] = lr

            opt.zero_grad(set_to_none=True)
            with torch.autocast(device_type=device.type, enabled=cfg.use_amp):
                loss, l_sp, l_loc, l_var, fr, _ = model(x_c, x_t, x_locs)
            scaler.scale(loss).backward()
            scaler.unscale_(opt)
            nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
            scaler.step(opt)
            scaler.update()
            model.ema_step(step, total_steps)

            for k, v in zip(["loss", "sp", "loc", "var", "fr"],
                             [loss, l_sp, l_loc, l_var, fr]):
                sums[k] += v.detach().item() * bs
            seen += bs
            step += 1
            if batch_i % 50 == 0:
                pbar.set_postfix(loss=f"{loss.item():.3f}", ema=f"{model.ema_d:.4f}")

        em = {k: v / seen for k, v in sums.items()}
        elapsed = time.time() - t0

        logs["epoch"].append(ep)
        for k_log, k_em in [("loss", "loss"), ("spatial", "sp"), ("local", "loc"),
                              ("var", "var"), ("fr", "fr")]:
            logs[k_log].append(em[k_em])
        logs["ema"].append(model.ema_d)
        logs["lr"].append(lr)

        print(f"[SSL {ep+1:02d}] loss={em['loss']:.4f} sp={em['sp']:.4f} "
              f"loc={em['loc']:.4f} fr={em['fr']:.4f} ema={model.ema_d:.4f} | {elapsed:.0f}s")

        knn_ood = None
        knn_id = None
        if (ep + 1) % cfg.eval_every == 0 or ep == cfg.ssl_epochs - 1:
            knn_ood, knn_id, _ = ssl_eval(model, f"ep={ep+1}")
            if knn_ood > best_knn:
                best_knn = knn_ood
                patience = cfg.ssl_patience
                torch.save(model.online.state_dict(), out / "best_ssl_encoder.pt")
                print(f"  ★ best OOD kNN: {best_knn:.4f}")
            else:
                patience -= 1
        logs["knn"].append(knn_ood)
        logs["knn_id"].append(knn_id)

        torch.save({
            "epoch": ep, "step": step,
            "online": model.online.state_dict(),
            "target": model.target.state_dict(),
            "optimizer": opt.state_dict(), "scaler": scaler.state_dict(),
            "best_knn": best_knn, "patience_left": patience, "ema_d": model.ema_d,
        }, resume_path)
        with open(out / "ssl_logs.json", "w") as f:
            json.dump(logs, f, indent=2)

        if patience <= 0:
            print("Early stopping SSL")
            break

    return logs, best_knn


ssl_logs, best_ssl_knn = ssl_train(cfg)
print(f"Best SSL kNN: {best_ssl_knn:.4f}")

# ============================================================
# CELL 9 — RECOVER SSL LOGS AFTER MANUALLY STOPPING CELL 8
# ============================================================

import json
from pathlib import Path
import matplotlib.pyplot as plt

run_dir = Path(cfg.out_dir)

logs_path = run_dir / "ssl_logs.json"
checkpoint_path = run_dir / "best_ssl_encoder.pt"

print("=" * 70)
print("RECOVERING SSL RUN")
print("=" * 70)
print("Run directory :", run_dir)
print("Logs file     :", logs_path)
print("Checkpoint    :", checkpoint_path)
print()

# ------------------------------------------------------------
# 1. Reload the SSL logs that Cell 8 saved
# ------------------------------------------------------------

if not logs_path.is_file():
    raise FileNotFoundError(
        f"Could not find SSL logs at:\n{logs_path}\n\n"
        "Do NOT rerun Cell 8 yet."
    )

with open(logs_path, "r") as f:
    ssl_logs = json.load(f)

print("✓ ssl_logs successfully restored")

# ------------------------------------------------------------
# 2. Confirm best SSL encoder exists
# ------------------------------------------------------------

if checkpoint_path.is_file():
    print("✓ best_ssl_encoder.pt found")
else:
    print("⚠ best_ssl_encoder.pt was NOT found")

# ------------------------------------------------------------
# 3. Show what was recovered
# ------------------------------------------------------------

print("\nRecovered SSL history:")

for key in ["loss", "spatial", "local", "var", "fr", "knn", "knn_id"]:
    vals = ssl_logs.get(key, [])

    if vals is None:
        vals = []

    print(f"{key:10s}: {len(vals)} recorded values")

# ------------------------------------------------------------
# 4. Plot recovered training curves
# ------------------------------------------------------------

for key in ["loss", "spatial", "local", "var", "fr", "knn", "knn_id"]:

    vals = [v for v in ssl_logs.get(key, []) if v is not None]

    xs = [
        e for e, v in zip(
            ssl_logs.get("epoch", []),
            ssl_logs.get(key, [])
        )
        if v is not None
    ]

    if not vals:
        continue

    # Fallback if epochs were not explicitly stored
    if len(xs) != len(vals):
        xs = list(range(1, len(vals) + 1))

    plt.figure(figsize=(7, 2.5))
    plt.plot(
        xs,
        vals,
        "o-" if len(vals) < 30 else "-"
    )

    plt.title(f"SSL {key}")
    plt.xlabel("Epoch")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()

print("\n" + "=" * 70)
print("SSL RECOVERY COMPLETE")
print("You can now continue to the next cell.")
print("=" * 70)

# =============================================================
# CELL 10 — Fine-tune with physics losses + HNM
# FIXED: advance OneCycleLR after each successful optimizer step.
# Automatically archive an old FT run whose scheduler never advanced.
# =============================================================
import shutil
import tempfile
from pathlib import Path

out_dir = Path(cfg.out_dir)
out_dir.mkdir(parents=True, exist_ok=True)
best_ssl_path = out_dir / "best_ssl_encoder.pt"
ft_resume = out_dir / "ft_resume.pt"
val_logits_path = out_dir / "val_logits_best.pt"

if not best_ssl_path.exists():
    raise FileNotFoundError(f"Saved SSL encoder not found: {best_ssl_path}")

# Read before modifying the model. Do not resume the stalled schedule.
resume_ckpt = None
if ft_resume.exists():
    resume_ckpt = torch.load(ft_resume, map_location="cpu", weights_only=False)
    saved_scheduler = resume_ckpt.get("scheduler", {})
    stalled_scheduler = (
        int(resume_ckpt.get("epoch", -1)) >= 0
        and int(saved_scheduler.get("last_epoch", 0)) <= 0
    )
    if stalled_scheduler:
        backup_dir = Path(tempfile.mkdtemp(prefix="ft_before_scheduler_fix_", dir=str(out_dir)))
        for filename in (
            "ft_resume.pt", "ft_logs.json", "best_classifier.pt",
            "val_logits_best.pt", "calibration.json",
        ):
            old_file = out_dir / filename
            if old_file.exists():
                shutil.move(str(old_file), str(backup_dir / filename))
        resume_ckpt = None
        print(f"Backed up old fine-tuning files to: {backup_dir}")
        print("Restarting fine-tuning from the saved best SSL encoder.")
    elif int(saved_scheduler.get("total_steps", -1)) != cfg.ft_epochs * len(ft_dl):
        raise ValueError(
            "The saved OneCycle schedule does not match ft_epochs and len(ft_dl). "
            "Restore the original settings before resuming this fine-tuning run."
        )

def focal_loss_fn(logits, y, gamma=1.5):
    ce = F.cross_entropy(logits, y, reduction="none", label_smoothing=cfg.label_smooth)
    return ((1.0 - torch.exp(-ce)) ** gamma * ce).mean()


def d4_transform(x, k):
    if k >= 4:
        x = torch.flip(x, dims=[3])
    rot = k % 4
    return torch.rot90(x, rot, dims=[2, 3]) if rot > 0 else x


def equivariance_loss(model, x):
    k = random.randint(1, 7)
    p_o = F.log_softmax(model(x), dim=-1)
    p_t = F.log_softmax(model(d4_transform(x, k)), dim=-1)
    return 0.5 * (F.kl_div(p_o, p_t, reduction="batchmean", log_target=True)
                  + F.kl_div(p_t, p_o, reduction="batchmean", log_target=True))


def anchor_pull_loss(z, y, anchors, margin=0.3):
    z_n = F.normalize(z, dim=-1)
    a_n = F.normalize(anchors, dim=-1)
    sims = z_n @ a_n.t()
    pull = (1.0 - sims.gather(1, y.unsqueeze(1)).squeeze(1)).mean()
    push = F.relu(sims.gather(1, (1 - y).unsqueeze(1)).squeeze(1) - (1.0 - margin)).mean()
    sep = F.relu((a_n[0] * a_n[1]).sum().abs() - margin)
    return pull + push + 0.5 * sep


class SAM:
    def __init__(self, base_optimizer, rho=0.05):
        self.base_optimizer = base_optimizer
        self.rho = rho
        self.param_groups = base_optimizer.param_groups
        self.state = base_optimizer.state
        self._e_ws = {}

    @torch.no_grad()
    def first_step(self):
        norm = torch.norm(torch.stack([p.grad.norm(p=2) for g in self.param_groups
                                         for p in g["params"] if p.grad is not None]), p=2)
        scale = self.rho / (norm + 1e-12)
        for g in self.param_groups:
            for p in g["params"]:
                if p.grad is None:
                    continue
                e_w = p.grad * scale.to(p)
                p.add_(e_w)
                self._e_ws[id(p)] = e_w

    @torch.no_grad()
    def second_step(self):
        for g in self.param_groups:
            for p in g["params"]:
                if id(p) in self._e_ws:
                    p.sub_(self._e_ws[id(p)])
        self._e_ws.clear()
        self.base_optimizer.step()

    def zero_grad(self, set_to_none=True):
        self.base_optimizer.zero_grad(set_to_none=set_to_none)


class ModelEMA:
    def __init__(self, model, decay=0.9995):
        self.decay = decay
        self.shadow = {k: v.detach().cpu().clone().float()
                       for k, v in model.state_dict().items() if v.dtype.is_floating_point}

    @torch.no_grad()
    def update(self, model):
        for k, v in model.state_dict().items():
            if k in self.shadow:
                self.shadow[k] = self.shadow[k].to('cpu').float().mul_(self.decay).add_(v.detach().cpu().float(), alpha=1.0 - self.decay)

    def apply_to(self, model):
        target = model.state_dict()
        cast = {k: v.to(target[k].dtype).to(target[k].device)
                for k, v in self.shadow.items() if k in target}
        full = {k: cast.get(k, target[k]) for k in target}
        model.load_state_dict(full)


class MultiScaleClassifier(nn.Module):
    def __init__(self, encoder, latent, num_classes=2, drop=0.30, use_anchors=True):
        super().__init__()
        self.encoder = encoder
        self.head = nn.Sequential(
            nn.Linear(latent, latent // 2), nn.GELU(), nn.Dropout(drop),
            nn.Linear(latent // 2, latent // 4), nn.GELU(), nn.Dropout(drop * 0.7),
            nn.Linear(latent // 4, num_classes))
        self.use_anchors = use_anchors
        if use_anchors:
            a = F.normalize(torch.randn(num_classes, latent), dim=-1)
            a[1] = F.normalize(a[1] - (a[1] * a[0]).sum() * a[0], dim=-1)
            self.anchors = nn.Parameter(a)

    def forward(self, x, return_z=False):
        fmap = self.encoder.features(x)
        z = self.encoder.pooled(fmap)
        logits = self.head(z)
        return (logits, z) if return_z else logits


@torch.inference_mode()
def mine_hard_negatives(clf_model, train_eval_dl, top_frac=0.10, min_prob=0.3):
    clf_model.eval()
    probs_l, labels_l = [], []
    for x, y in tqdm(train_eval_dl, desc="HNM", leave=False):
        x = x.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
        lg = tta_logits(clf_model, x) if cfg.tta else clf_model(x)
        probs_l.append(torch.softmax(lg, dim=-1)[:, 1].cpu().numpy())
        labels_l.append(y.numpy())
    probs_cat = np.concatenate(probs_l)
    labels_cat = np.concatenate(labels_l)
    neg_mask = (labels_cat == 0)
    n_hard = min(int(len(probs_cat) * top_frac), int(neg_mask.sum()))
    if n_hard == 0:
        return np.array([], dtype=int)
    neg_probs = np.where(neg_mask, probs_cat, -1)
    hard = np.argpartition(-neg_probs, n_hard - 1)[:n_hard]
    hard = hard[neg_probs[hard] > min_prob]
    print(f"  mined {len(hard)} hard negs (max={neg_probs[hard].max() if len(hard) > 0 else 0:.3f})")
    return hard


sd = torch.load(best_ssl_path, map_location=device, weights_only=True)
sd = {k.replace("_orig_mod.", ""): v for k, v in sd.items()}
model.online.load_state_dict(sd)
print("Loaded best SSL encoder")

for attr in ["target", "pred", "masker", "ssl_proj_online", "ssl_proj_target"]:
    if hasattr(model, attr):
        delattr(model, attr)
torch.cuda.empty_cache()

clf_model = MultiScaleClassifier(model.online, cfg.latent, cfg.num_classes,
                                  cfg.head_drop, use_anchors=cfg.use_anchors).to(device)
clf_model = clf_model.to(memory_format=torch.channels_last)
print(f"Classifier: {sum(p.numel() for p in clf_model.parameters())/1e6:.2f}M params")

for p in clf_model.encoder.parameters():
    p.requires_grad = False

base_opt = torch.optim.AdamW([
    {"params": clf_model.encoder.parameters(), "lr": cfg.ft_lr * 0.3, "weight_decay": cfg.wd},
    {"params": clf_model.head.parameters(), "lr": cfg.ft_lr, "weight_decay": cfg.wd * 0.2},
])
if cfg.use_anchors:
    base_opt.add_param_group({"params": [clf_model.anchors], "lr": cfg.ft_lr * 0.5, "weight_decay": 0.0})

max_lrs = [cfg.ft_lr * 0.3, cfg.ft_lr] + ([cfg.ft_lr * 0.5] if cfg.use_anchors else [])
sch = torch.optim.lr_scheduler.OneCycleLR(base_opt, max_lr=max_lrs,
                                           epochs=cfg.ft_epochs, steps_per_epoch=len(ft_dl),
                                           pct_start=0.2, anneal_strategy='cos')
scaler = torch.amp.GradScaler("cuda", enabled=cfg.use_amp)
sam = SAM(base_opt, rho=cfg.sam_rho)
ema = ModelEMA(clf_model, decay=cfg.model_ema_decay)
ema_started = False

ft_logs = {"epoch": [], "loss": [], "acc": [], "auc": [], "ema_auc": []}
best_ft_auc = -1.0
best_ft_preds = None
patience = cfg.ft_patience
hard_neg_indices = np.array([], dtype=int)
HNM_START = 4
HNM_REFRESH = 3
HNM_FRAC = 0.25

start_ep = 0
if resume_ckpt is not None:
    # Let an incompatible checkpoint raise an error instead of silently
    # continuing with a partially restored model or optimizer.
    ckpt = resume_ckpt
    clf_model.load_state_dict(ckpt["model"])
    base_opt.load_state_dict(ckpt["optimizer"])
    sch.load_state_dict(ckpt["scheduler"])
    scaler.load_state_dict(ckpt["scaler"])
    start_ep = ckpt["epoch"] + 1
    best_ft_auc = ckpt["best_ft_auc"]
    patience = ckpt["patience_left"]
    if ckpt.get("best_ft_preds"):
        bp = ckpt["best_ft_preds"]
        best_ft_preds = (bp["preds"], bp["trues"], bp["probs"])
    if "ema_shadow" in ckpt:
        ema.shadow = ckpt["ema_shadow"]
        ema_started = ckpt.get("ema_started", False)
    if "hard_neg_indices" in ckpt:
        hard_neg_indices = np.array(ckpt["hard_neg_indices"], dtype=int)
    ft_logs_p = out_dir / "ft_logs.json"
    if ft_logs_p.exists():
        with open(ft_logs_p) as f:
            ft_logs = json.load(f)
    if start_ep >= cfg.finetune_freeze_epochs:
        for p in clf_model.encoder.parameters():
            p.requires_grad = True
    print(f"Resumed FT at epoch {start_ep}, best_auc={best_ft_auc:.4f}")
    del ckpt
resume_ckpt = None

for ep in range(start_ep, cfg.ft_epochs):
    if ep == cfg.finetune_freeze_epochs:
        for p in clf_model.encoder.parameters():
            p.requires_grad = True
        print("Unfroze encoder")

    if ep >= HNM_START and (ep - HNM_START) % HNM_REFRESH == 0:
        hard_neg_indices = mine_hard_negatives(clf_model, tr_dl)

    use_equiv = ep >= cfg.equiv_warmup_epochs
    use_sam = cfg.use_sam and ep >= cfg.sam_start_epoch
    use_hnm = len(hard_neg_indices) > 0

    clf_model.train()
    sum_loss = sum_focal = 0.0
    seen = 0
    t0 = time.time()
    tag = " [SAM]" if use_sam else ""
    if use_hnm:
        tag += " [HNM]"
    pbar = tqdm(ft_dl, desc=f"FT {ep+1}/{cfg.ft_epochs}{tag}")

    for batch_i, (x, y) in enumerate(pbar):
        if use_hnm and batch_i % 2 == 0:
            n_h = int(x.size(0) * HNM_FRAC)
            hn = np.random.choice(hard_neg_indices, size=min(n_h, len(hard_neg_indices)), replace=False)
            hn_imgs, hn_lbls = [], []
            for hi in hn:
                im, lb = ft_train_ds[int(hi)]
                hn_imgs.append(im); hn_lbls.append(lb)
            if hn_imgs:
                n_h = len(hn_imgs)
                hn_x = torch.stack(hn_imgs, dim=0).to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
                hn_y = torch.tensor(hn_lbls, dtype=torch.long, device=device)
                x = x.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
                y = y.to(device, non_blocking=True)
                x = torch.cat([hn_x, x[n_h:]], dim=0)
                y = torch.cat([hn_y, y[n_h:]], dim=0)
            else:
                x = x.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
                y = y.to(device, non_blocking=True)
        else:
            x = x.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
            y = y.to(device, non_blocking=True)
        bs = x.size(0)

        def compute_loss():
            if cfg.use_anchors:
                logits, z = clf_model(x, return_z=True)
            else:
                logits = clf_model(x); z = None
            loss = focal_loss_fn(logits, y, gamma=cfg.focal_gamma)
            if z is not None:
                loss = loss + cfg.lam_anchor * anchor_pull_loss(z, y, clf_model.anchors, cfg.anchor_margin)
            if use_equiv and random.random() < cfg.equiv_prob:
                loss = loss + cfg.lam_equiv * equivariance_loss(clf_model, x)
            return loss, logits

        base_opt.zero_grad(set_to_none=True)
        optimizer_stepped = True
        if not use_sam:
            with torch.autocast(device_type=device.type, enabled=cfg.use_amp):
                loss, logits = compute_loss()
                l_focal = focal_loss_fn(logits.detach(), y, gamma=cfg.focal_gamma)

        if use_sam:
            with torch.autocast(device_type=device.type, enabled=cfg.use_amp):
                loss, logits = compute_loss()
                l_focal = focal_loss_fn(logits.detach(), y, gamma=cfg.focal_gamma)
            loss.backward()
            nn.utils.clip_grad_norm_(clf_model.parameters(), cfg.grad_clip)
            sam.first_step()
            base_opt.zero_grad(set_to_none=True)
            with torch.autocast(device_type=device.type, enabled=cfg.use_amp):
                loss2, _ = compute_loss()
            loss2.backward()
            nn.utils.clip_grad_norm_(clf_model.parameters(), cfg.grad_clip)
            sam.second_step()
        else:
            old_scale = scaler.get_scale()
            scaler.scale(loss).backward()
            scaler.unscale_(base_opt)
            nn.utils.clip_grad_norm_(clf_model.parameters(), cfg.grad_clip)
            scaler.step(base_opt)
            scaler.update()
            optimizer_stepped = scaler.get_scale() >= old_scale

        # FIX: advance once after either optimizer path.
        # AMP can skip an update on overflow; do not advance in that case.
        if optimizer_stepped:
            sch.step()

        if optimizer_stepped and ep >= cfg.model_ema_warmup:
            if not ema_started:
                ema.shadow = {k: v.detach().cpu().clone().float()
                              for k, v in clf_model.state_dict().items() if v.dtype.is_floating_point}
                ema_started = True
            ema.update(clf_model)

        sum_loss += loss.item() * bs
        sum_focal += l_focal.item() * bs
        seen += bs
        pbar.set_postfix(focal=f"{l_focal.item():.3f}", lr=f"{base_opt.param_groups[1]['lr']:.2e}")

    clf_model.eval()
    raw_logits_list, raw_labels_list = [], []
    with torch.inference_mode():
        for xv, yv in va_dl:
            xv = xv.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
            lg = tta_logits(clf_model, xv) if cfg.tta else clf_model(xv)
            raw_logits_list.append(lg.cpu())
            raw_labels_list.append(yv)
    raw_logits = torch.cat(raw_logits_list)
    raw_labels = torch.cat(raw_labels_list)
    val_preds = raw_logits.argmax(1).numpy()
    val_trues = raw_labels.numpy()
    val_probs = torch.softmax(raw_logits, dim=1)[:, 1].numpy()
    val_acc = (val_preds == val_trues).mean()
    val_auc = roc_auc_score(val_trues, val_probs)

    ema_auc = None
    ema_preds = ema_probs = ema_logits = None
    if ema_started:
        raw_state = copy.deepcopy(clf_model.state_dict())
        ema.apply_to(clf_model)
        clf_model.eval()
        ema_logits_list = []
        with torch.inference_mode():
            for xv, _ in va_dl:
                xv = xv.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
                lg = tta_logits(clf_model, xv) if cfg.tta else clf_model(xv)
                ema_logits_list.append(lg.cpu())
        ema_logits = torch.cat(ema_logits_list)
        ema_preds = ema_logits.argmax(1).numpy()
        ema_probs = torch.softmax(ema_logits, dim=1)[:, 1].numpy()
        ema_auc = roc_auc_score(val_trues, ema_probs)
        clf_model.load_state_dict(raw_state)

    ft_logs["epoch"].append(ep)
    ft_logs["loss"].append(sum_loss / seen)
    ft_logs["acc"].append(float(val_acc))
    ft_logs["auc"].append(float(val_auc))
    ft_logs["ema_auc"].append(float(ema_auc) if ema_auc is not None else None)

    elapsed = time.time() - t0
    ema_str = f" ema_auc={ema_auc:.4f}" if ema_auc is not None else ""
    print(f"[FT {ep+1:02d}{tag}] focal={sum_focal/seen:.4f} acc={val_acc:.4f} auc={val_auc:.4f}{ema_str} | {elapsed:.0f}s")

    cand_auc = val_auc
    cand_preds = (val_preds.copy(), val_trues.copy(), val_probs.copy())
    cand_logits = raw_logits
    cand_is_ema = False
    if ema_auc is not None and ema_auc > val_auc:
        cand_auc = ema_auc
        cand_preds = (ema_preds.copy(), val_trues.copy(), ema_probs.copy())
        cand_logits = ema_logits
        cand_is_ema = True

    if cand_auc > best_ft_auc:
        best_ft_auc = cand_auc
        best_ft_preds = cand_preds
        patience = cfg.ft_patience
        if cand_is_ema:
            ema_state = {
                k: ema.shadow.get(k, v).detach().cpu().to(dtype=v.dtype).clone()
                for k, v in clf_model.state_dict().items()
            }
            torch.save(ema_state, Path(cfg.out_dir) / "best_classifier.pt")
        else:
            torch.save(clf_model.state_dict(), Path(cfg.out_dir) / "best_classifier.pt")
        torch.save({"logits": cand_logits.clone(), "labels": raw_labels}, val_logits_path)
        print(f"  ★ best AUC: {best_ft_auc:.4f}")
    else:
        patience -= 1

    torch.save({
        "epoch": ep,
        "model": clf_model.state_dict(),
        "optimizer": base_opt.state_dict(),
        "scheduler": sch.state_dict(),
        "scaler": scaler.state_dict(),
        "best_ft_auc": best_ft_auc,
        "patience_left": patience,
        "ema_shadow": ema.shadow,
        "ema_started": ema_started,
        "hard_neg_indices": hard_neg_indices.tolist(),
        "best_ft_preds": {"preds": best_ft_preds[0], "trues": best_ft_preds[1], "probs": best_ft_preds[2]} if best_ft_preds else None,
    }, ft_resume)
    with open(Path(cfg.out_dir) / "ft_logs.json", "w") as f:
        json.dump(ft_logs, f, indent=2)

    if patience <= 0:
        print("Early stopping FT")
        break

print(f"\nBest AUC: {best_ft_auc:.4f}")

if val_logits_path.exists():
    cached = torch.load(val_logits_path, map_location="cpu")
    val_logits_cat = cached["logits"]
    val_labels_cat = cached["labels"]
else:
    val_logits_list, val_labels_list = [], []
    with torch.inference_mode():
        for xv, yv in va_dl:
            xv = xv.to(device, non_blocking=True).contiguous(memory_format=torch.channels_last)
            lg = tta_logits(clf_model, xv) if cfg.tta else clf_model(xv)
            val_logits_list.append(lg.cpu())
            val_labels_list.append(yv)
    val_logits_cat = torch.cat(val_logits_list)
    val_labels_cat = torch.cat(val_labels_list)

temperature = nn.Parameter(torch.ones(1) * 1.5)
temp_opt = torch.optim.LBFGS([temperature], lr=0.01, max_iter=100)


def temp_eval():
    temp_opt.zero_grad()
    loss = F.cross_entropy(val_logits_cat / temperature, val_labels_cat)
    loss.backward()
    return loss


temp_opt.step(temp_eval)
learned_temperature = float(temperature.item())
val_probs_cal = torch.softmax(val_logits_cat / learned_temperature, dim=1)[:, 1].detach().numpy()
val_trues_cal = val_labels_cat.numpy()

candidates = np.arange(0.20, 0.80, 0.005)
band_f1s = []
for t in candidates:
    win = np.arange(max(0.05, t - 0.02), min(0.95, t + 0.02), 0.005)
    f1s = [f1_score(val_trues_cal, (val_probs_cal >= tw).astype(int)) for tw in win]
    band_f1s.append(np.mean(f1s))
best_thresh = float(candidates[int(np.argmax(band_f1s))])

with open(Path(cfg.out_dir) / "calibration.json", "w") as f:
    json.dump({"temperature": learned_temperature, "threshold": best_thresh}, f, indent=2)

print(f"T={learned_temperature:.4f} threshold={best_thresh:.3f}")
val_opt = (val_probs_cal >= best_thresh).astype(int)
report_metrics(val_opt, val_trues_cal, val_probs_cal, label="VAL")

print("\nLearned toroidal blend:")
for name, m in clf_model.named_modules():
    if isinstance(m, TConvHybrid):
        print(f"  {name}: circ={torch.sigmoid(m.alpha).item():.3f}")

print("\nLearned spike beta:")
for name, m in clf_model.named_modules():
    if isinstance(m, SpikeGateV2):
        print(f"  {name}: beta={m.beta.item():.3f}")

# =============================================================
# CELL 11 — Fine-tune curves + validation report
# =============================================================
fig, axes = plt.subplots(1, 3, figsize=(13, 3.5))
axes[0].plot(ft_logs["epoch"], ft_logs["loss"], "o-")
axes[0].set_title("Loss")
axes[1].plot(ft_logs["epoch"], ft_logs["acc"], "o-", color="green")
axes[1].set_title("Val Acc")
axes[2].plot(ft_logs["epoch"], ft_logs["auc"], "o-", color="red")
axes[2].set_title("Val AUC")
for a in axes:
    a.set_xlabel("Epoch"); a.grid(alpha=0.3)
plt.tight_layout(); plt.show()

if best_ft_preds:
    report_metrics(*best_ft_preds, label="BEST VAL")
    plot_roc(best_ft_preds[1], best_ft_preds[2], label="Val")
    plot_cm(best_ft_preds[0], best_ft_preds[1], label="Val")

# =============================================================
# CELL 12 — Final evaluation of saved best classifier
# =============================================================
import copy
import gc
import hashlib
import json
import time
import types
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F

from IPython.display import display
from torch.utils.data import DataLoader, Subset
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    recall_score,
    precision_score,
    f1_score,
)

out_dir = Path(cfg.out_dir)
out_dir.mkdir(parents=True, exist_ok=True)

analysis_dir = out_dir / "analysis"
analysis_dir.mkdir(exist_ok=True)

best_clf = out_dir / "best_classifier.pt"

if not best_clf.is_file():
    raise FileNotFoundError(
        f"Best classifier not found. Finish Cell 10 first: {best_clf}"
    )

# Load the best epoch, not necessarily the most recent epoch
sd = torch.load(best_clf, map_location="cpu", weights_only=True)
sd = {k.replace("_orig_mod.", ""): v for k, v in sd.items()}

clf_model.load_state_dict(sd, strict=True)
del sd

clf_model.eval()
checkpoint_sha256 = hashlib.sha256(best_clf.read_bytes()).hexdigest()

# Final evaluation settings
FINAL_USE_TTA = bool(cfg.tta)
FINAL_STRONG_TTA = True
EVAL_BATCH_SIZE = min(64, int(cfg.eval_bs))

# Keep this fixed across all model seeds for fair comparison
ANALYSIS_SEED = 42


def analysis_loader(dataset, indices=None):
    if indices is not None:
        dataset = Subset(dataset, np.asarray(indices).tolist())

    workers = min(2, max(0, int(cfg.num_workers)))

    return DataLoader(
        dataset,
        batch_size=EVAL_BATCH_SIZE,
        shuffle=False,
        num_workers=workers,
        pin_memory=(device.type == "cuda"),
        persistent_workers=False,
        generator=torch.Generator().manual_seed(ANALYSIS_SEED),
    )


@torch.inference_mode()
def collect_logits(net, loader, label, use_tta=False, strong=False):
    net.eval()

    logits_list = []
    labels_list = []

    for x, y in tqdm(loader, desc=label, leave=False):
        x = x.to(
            device, non_blocking=True
        ).contiguous(memory_format=torch.channels_last)

        if use_tta:
            logits = tta_logits(net, x, strong=strong)
        else:
            logits = net(x)

        logits_list.append(logits.float().cpu())
        labels_list.append(y.long().cpu())

    if not logits_list:
        raise ValueError(f"Empty evaluation loader: {label}")

    return torch.cat(logits_list), torch.cat(labels_list)


# Fit calibration using validation only
selection_ds = ood_val_ds if cfg.select_on_ood else id_val_ds
selection_name = "ood_val" if cfg.select_on_ood else "id_val"

selection_logits, selection_labels = collect_logits(
    clf_model,
    analysis_loader(selection_ds),
    "Calibration validation",
    FINAL_USE_TTA,
    FINAL_STRONG_TTA,
)

selection_logits = selection_logits.clone().float()
selection_labels = selection_labels.clone().long()

if not torch.isfinite(selection_logits).all():
    raise ValueError("Nonfinite validation logits; calibration cannot proceed.")


# Positive temperature parameter
log_temperature = torch.nn.Parameter(
    torch.tensor(np.log(1.5), dtype=torch.float32)
)

temperature_opt = torch.optim.LBFGS(
    [log_temperature],
    lr=0.1,
    max_iter=100,
    line_search_fn="strong_wolfe",
)


def final_temperature_closure():
    temperature_opt.zero_grad()

    temperature = log_temperature.clamp(
        np.log(0.05), np.log(20.0)
    ).exp()

    loss = F.cross_entropy(
        selection_logits / temperature,
        selection_labels,
    )

    loss.backward()
    return loss


temperature_opt.step(final_temperature_closure)

learned_temperature = float(
    log_temperature.detach()
    .clamp(np.log(0.05), np.log(20.0))
    .exp()
)

uncalibrated_nll = float(
    F.cross_entropy(selection_logits, selection_labels)
)

calibrated_nll = float(
    F.cross_entropy(
        selection_logits / learned_temperature,
        selection_labels,
    )
)

# Do not keep calibration if it makes validation NLL worse
if not np.isfinite(calibrated_nll) or calibrated_nll > uncalibrated_nll:
    learned_temperature = 1.0


selection_probs = torch.softmax(
    selection_logits / learned_temperature,
    dim=1,
)[:, 1].numpy()

selection_trues = selection_labels.numpy()

# Select decision threshold on validation only
candidates = np.arange(0.20, 0.80, 0.005)
band_f1s = []

for threshold in candidates:
    window = np.arange(
        max(0.05, threshold - 0.02),
        min(0.95, threshold + 0.02),
        0.005,
    )

    band_f1s.append(
        np.mean([
            f1_score(
                selection_trues,
                selection_probs >= t,
                zero_division=0,
            )
            for t in window
        ])
    )

best_thresh = float(candidates[int(np.argmax(band_f1s))])

final_protocol = {
    "seed": int(cfg.seed),
    "checkpoint_sha256": checkpoint_sha256,
    "tta": (
        "d4_plus_zoom_16_views"
        if FINAL_USE_TTA
        else "none"
    ),
    "inference_batch_size": EVAL_BATCH_SIZE,
    "calibration_split": selection_name,
    "temperature": learned_temperature,
    "threshold": best_thresh,
}

with open(out_dir / "calibration_final.json", "w") as f:
    json.dump(final_protocol, f, indent=2)


def split_metrics(logits, labels, label):
    trues = labels.cpu().numpy()

    probs = torch.softmax(
        logits.float() / learned_temperature,
        dim=1,
    )[:, 1].cpu().numpy()

    preds = (probs >= best_thresh).astype(np.int64)

    return {
        "label": label,
        "n": int(len(trues)),
        "auc": float(roc_auc_score(trues, probs)),
        "acc": float(accuracy_score(trues, preds)),
        "sens": float(
            recall_score(
                trues, preds,
                pos_label=1,
                zero_division=0,
            )
        ),
        "spec": float(
            recall_score(
                trues, preds,
                pos_label=0,
                zero_division=0,
            )
        ),
        "prec": float(
            precision_score(
                trues, preds,
                zero_division=0,
            )
        ),
        "f1": float(
            f1_score(
                trues, preds,
                zero_division=0,
            )
        ),
        "preds": preds,
        "trues": trues,
        "probs": probs,
    }


split_results = {}

for key, dataset, label in (
    (
        "id_val",
        id_val_ds,
        "ID VAL — training hospitals",
    ),
    (
        "ood_val",
        ood_val_ds,
        "OOD VAL — held-out validation hospital",
    ),
    (
        "ood_test",
        ood_test_ds,
        "OOD TEST — final unseen test hospital",
    ),
):
    if key == selection_name:
        logits, labels = selection_logits, selection_labels
    else:
        logits, labels = collect_logits(
            clf_model,
            analysis_loader(dataset),
            label,
            FINAL_USE_TTA,
            FINAL_STRONG_TTA,
        )

    split_results[key] = split_metrics(
        logits, labels, label
    )

    np.savez_compressed(
        analysis_dir / f"{key}_predictions.npz",
        **{
            name: split_results[key][name]
            for name in ("preds", "trues", "probs")
        },
    )


id_val_res = split_results["id_val"]
ood_val_res = split_results["ood_val"]
test_res = split_results["ood_test"]

shift_gap = id_val_res["acc"] - test_res["acc"]

summary = {
    key: {
        k: v
        for k, v in result.items()
        if k not in ("preds", "trues", "probs")
    }
    for key, result in split_results.items()
}


def completed_epochs(filename):
    path = out_dir / filename

    if not path.exists():
        return None

    with open(path) as f:
        return len(json.load(f).get("epoch", []))


with open(out_dir / "camelyon17_results.json", "w") as f:
    json.dump(
        {
            "version": "tsj-v2.2-camelyon17-wilds-seed789",
            **final_protocol,
            "ssl_epochs_requested": int(cfg.ssl_epochs),
            "ft_epochs_requested": int(cfg.ft_epochs),
            "ssl_epochs_completed": completed_epochs(
                "ssl_logs.json"
            ),
            "ft_epochs_completed": completed_epochs(
                "ft_logs.json"
            ),
            **summary,
            "domain_shift_gap": float(shift_gap),
        },
        f,
        indent=2,
    )


print(
    f"Seed {cfg.seed} | best classifier loaded | "
    f"{final_protocol['tta']}"
)

print(
    f"Validation-fitted temperature="
    f"{learned_temperature:.4f}, "
    f"threshold={best_thresh:.3f}"
)

display(
    pd.DataFrame(summary).T[
        ["n", "acc", "auc", "sens", "spec", "prec", "f1"]
    ]
)

print(
    f"ID accuracy minus OOD test accuracy: "
    f"{shift_gap:+.4f}"
)

plot_roc(
    test_res["trues"],
    test_res["probs"],
    label="OOD Test",
)

plot_cm(
    test_res["preds"],
    test_res["trues"],
    label="OOD Test",
)

print(f"Saved final evaluation to {out_dir}")

# =============================================================
# CELL 13 — UMAP by class, hospital and split
# =============================================================
import importlib.metadata
import subprocess
import sys

try:
    import umap
except ModuleNotFoundError as exc:
    if exc.name != "umap":
        raise

    subprocess.check_call([
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "umap-learn",
    ])

    import umap


UMAP_SAMPLES_PER_SPLIT = 3000

# Test data is used only for descriptive visualisation after
# final testing. It is not used for model selection or training.
UMAP_INCLUDE_TEST = True


def make_umap():
    sources = [
        ("ID val", id_val_ds),
        ("OOD val", ood_val_ds),
    ]

    if UMAP_INCLUDE_TEST:
        sources.append(("OOD test", ood_test_ds))

    fields = list(wilds_dataset.metadata_fields)

    hospital_name = next(
        (
            name
            for name in ("hospital", "center")
            if name in fields
        ),
        None,
    )

    if hospital_name is None:
        raise ValueError(
            f"Hospital metadata field not found: {fields}"
        )

    hospital_col = fields.index(hospital_name)

    features = []
    frames = []

    clf_model.eval()

    for split_name, dataset in sources:
        indices = np.random.RandomState(
            ANALYSIS_SEED
        ).choice(
            len(dataset),
            min(UMAP_SAMPLES_PER_SPLIT, len(dataset)),
            replace=False,
        )

        subset = dataset.subset

        centers = subset.metadata_array[
            indices, hospital_col
        ].cpu().numpy()

        expected_labels = subset.y_array[
            indices
        ].cpu().numpy().reshape(-1)

        batch_features = []
        batch_labels = []

        with torch.inference_mode():
            loader = analysis_loader(dataset, indices)

            for x, y in tqdm(
                loader,
                desc=f"UMAP {split_name}",
            ):
                x = x.to(device).contiguous(
                    memory_format=torch.channels_last
                )

                fmap = clf_model.encoder.features(x)
                z = clf_model.encoder.multi_scale_pool(fmap)

                batch_features.append(
                    z.float().cpu().numpy()
                )

                batch_labels.append(y.numpy())

        labels = np.concatenate(batch_labels)

        if not np.array_equal(labels, expected_labels):
            raise ValueError(
                "Image labels and hospital metadata "
                "are misaligned."
            )

        features.append(
            np.concatenate(batch_features)
        )

        frames.append(
            pd.DataFrame({
                "split": split_name,
                "subset_index": indices,
                "class": labels.astype(int),
                "hospital": centers.astype(int),
            })
        )

    features = np.concatenate(features).astype(
        np.float32
    )

    frame = pd.concat(frames, ignore_index=True)

    reducer = umap.UMAP(
        n_neighbors=min(30, len(features) - 1),
        min_dist=0.3,
        metric="cosine",
        random_state=ANALYSIS_SEED,
        n_jobs=1,
        low_memory=True,
    )

    # Labels are not passed into UMAP
    embedding = reducer.fit_transform(features)

    frame["umap_1"] = embedding[:, 0]
    frame["umap_2"] = embedding[:, 1]

    fig, axes = plt.subplots(
        1, 3, figsize=(17, 5)
    )

    for ax, column, title in zip(
        axes,
        ("class", "hospital", "split"),
        ("By class", "By hospital", "By split"),
    ):
        values = sorted(frame[column].unique())

        for i, value in enumerate(values):
            mask = frame[column].to_numpy() == value

            if column == "class":
                label = (
                    "Normal" if value == 0 else "Tumour"
                )
            elif column == "hospital":
                label = f"Hospital {value}"
            else:
                label = str(value)

            ax.scatter(
                embedding[mask, 0],
                embedding[mask, 1],
                s=4,
                alpha=0.45,
                color=plt.get_cmap("tab10")(i),
                label=label,
            )

        ax.set_title(title)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.legend(
            markerscale=3,
            fontsize=9,
            frameon=False,
        )

    fig.suptitle(
        f"TSG-JEPA seed {cfg.seed} — "
        "saved best classifier"
    )

    fig.text(
        0.5,
        0.01,
        "Descriptive 2D projection; clustering does "
        "not prove domain invariance.",
        ha="center",
        fontsize=9,
    )

    fig.tight_layout(
        rect=(0, 0.04, 1, 0.94)
    )

    fig.savefig(
        analysis_dir / "umap_embeddings.png",
        dpi=220,
        bbox_inches="tight",
    )

    frame.to_csv(
        analysis_dir / "umap_points.csv",
        index=False,
    )

    np.savez_compressed(
        analysis_dir / "umap_features.npz",
        features=features,
        embedding=embedding,
    )

    with open(
        analysis_dir / "umap_protocol.json",
        "w",
    ) as f:
        json.dump(
            {
                "training_seed_declared": int(cfg.seed),
                "analysis_seed": ANALYSIS_SEED,
                "checkpoint_sha256": checkpoint_sha256,
                "feature_stage": (
                    "encoder.multi_scale_pool "
                    "before projection"
                ),
                "sample_count": int(len(frame)),
                "includes_test": UMAP_INCLUDE_TEST,
                "umap_version": (
                    importlib.metadata.version(
                        "umap-learn"
                    )
                ),
                "metric": "cosine",
                "min_dist": 0.3,
                "n_neighbors": reducer.n_neighbors,
                "label_usage": (
                    "plot colours only; joint "
                    "unsupervised fit on displayed splits"
                ),
            },
            f,
            indent=2,
        )

    plt.show()
    plt.close(fig)

    print(
        "Saved UMAP figure, coordinates and "
        f"features to {analysis_dir}"
    )


make_umap()

# =============================================================
# CELL 14 — Component sensitivity diagnostics
# OOD validation only; no retraining
# =============================================================
DIAGNOSTIC_SAMPLES = 2000


def _identity_forward(self, x):
    return x


def _circular_forward(self, x):
    return self.conv_circ(x)


def _reflection_forward(self, x):
    return self.conv_ref(x)


def _mean_only_pool(self, fmap):
    mean = fmap.mean(dim=(2, 3))

    # Repeat mean to preserve the trained projection's
    # expected input dimensions.
    return torch.cat([mean, mean, mean], dim=1)


def run_component_diagnostics():
    indices = np.random.RandomState(
        ANALYSIS_SEED
    ).choice(
        len(ood_val_ds),
        min(DIAGNOSTIC_SAMPLES, len(ood_val_ds)),
        replace=False,
    )

    variants = [
        (
            "baseline",
            "Learned model — single view",
        ),
        (
            "circular",
            "Circular branch only",
        ),
        (
            "reflection",
            "Reflection branch only",
        ),
        (
            "half",
            "50/50 branch blend",
        ),
        (
            "no_gate",
            "Spike gates bypassed",
        ),
        (
            "no_se",
            "SE bypassed with identity",
        ),
        (
            "mean_pool",
            "Mean repeated into all pooling branches",
        ),
    ]

    if FINAL_USE_TTA:
        variants.append(
            (
                "tta",
                "Learned model — 16-view TTA",
            )
        )

    rows = []
    arrays = {"subset_indices": indices}
    original_labels = None

    for key, label in variants:
        probe = copy.deepcopy(clf_model).eval()
        probe.requires_grad_(False)
        started = time.time()

        try:
            for module in probe.modules():
                if isinstance(module, TConvHybrid):
                    if key == "circular":
                        module.forward = types.MethodType(
                            _circular_forward,
                            module,
                        )

                    elif key == "reflection":
                        module.forward = types.MethodType(
                            _reflection_forward,
                            module,
                        )

                    elif key == "half":
                        with torch.no_grad():
                            module.alpha.zero_()

                if (
                    key == "no_gate"
                    and isinstance(module, SpikeGateV2)
                ):
                    module.forward = types.MethodType(
                        _identity_forward,
                        module,
                    )

                if (
                    key == "no_se"
                    and isinstance(module, SqueezeExcite)
                ):
                    module.forward = types.MethodType(
                        _identity_forward,
                        module,
                    )

            if key == "mean_pool":
                probe.encoder.multi_scale_pool = (
                    types.MethodType(
                        _mean_only_pool,
                        probe.encoder,
                    )
                )

            logits, labels = collect_logits(
                probe,
                analysis_loader(ood_val_ds, indices),
                label,
                use_tta=(key == "tta"),
                strong=FINAL_STRONG_TTA,
            )

            trues = labels.numpy()

            if original_labels is None:
                original_labels = trues.copy()
                arrays["labels"] = original_labels

            elif not np.array_equal(
                trues, original_labels
            ):
                raise ValueError(
                    "Diagnostic samples changed "
                    "between variants."
                )

            preds = logits.argmax(1).numpy()

            # Binary logit margin preserves ranking
            # without softmax saturation.
            scores = (
                logits[:, 1] - logits[:, 0]
            ).numpy()

            rows.append({
                "variant": label,
                "n": int(len(trues)),
                "acc": float(
                    accuracy_score(trues, preds)
                ),
                "auc": float(
                    roc_auc_score(trues, scores)
                ),
                "seconds": round(
                    time.time() - started,
                    1,
                ),
            })

            arrays[f"{key}_preds"] = preds
            arrays[f"{key}_scores"] = scores

        finally:
            del probe
            gc.collect()

            if device.type == "cuda":
                torch.cuda.empty_cache()

    table = pd.DataFrame(rows)

    table["delta_acc"] = (
        table["acc"] - table.loc[0, "acc"]
    )

    table["delta_auc"] = (
        table["auc"] - table.loc[0, "auc"]
    )

    table.to_csv(
        analysis_dir / "component_sensitivity.csv",
        index=False,
    )

    np.savez_compressed(
        analysis_dir /
        "component_sensitivity_predictions.npz",
        **arrays,
    )

    with open(
        analysis_dir / "component_sensitivity.json",
        "w",
    ) as f:
        json.dump(
            {
                "training_seed_declared": int(cfg.seed),
                "sampling_seed": ANALYSIS_SEED,
                "checkpoint_sha256": checkpoint_sha256,
                "split": "ood_val",
                "diagnostic_sample_size": int(
                    len(indices)
                ),
                "retraining": False,
                "prediction_rule": (
                    "argmax; no threshold fitting "
                    "for diagnostic variants"
                ),
                "structural_probe_tta": False,
                "tta_comparison_views": (
                    16 if FINAL_USE_TTA else 0
                ),
                "auc_score": (
                    "tumour minus normal logit"
                ),
                "limitations": [
                    (
                        "Post-training sensitivity does "
                        "not establish benefit from "
                        "training with a component."
                    ),
                    (
                        "Circular and reflection branches "
                        "have different learned weights; "
                        "this does not isolate padding alone."
                    ),
                    (
                        "Small sampled differences are not "
                        "evidence of statistical significance."
                    ),
                ],
                "results": table.to_dict(
                    orient="records"
                ),
            },
            f,
            indent=2,
        )

    display(table)

    print(
        "Negative deltas indicate lower performance "
        "after that intervention."
    )

    print(
        "True architecture ablations require separately "
        "trained variants with matched protocols and seeds."
    )

    print(
        f"Saved diagnostics to {analysis_dir}"
    )


run_component_diagnostics()

# =============================================================
# CELL 15 — Optional memory cleanup
# =============================================================
for _cleanup_name in (
    "base_opt",
    "sam",
    "scaler",
    "ema",
    "temp_opt",
    "temperature_opt",
    "loss",
    "loss2",
    "logits",
    "l_focal",
    "raw_state",
    "ema_state",
    "compute_loss",
    "ckpt",
    "resume_ckpt",
    "x",
    "y",
    "xv",
    "yv",
    "hn_x",
    "hn_y",
):
    globals().pop(_cleanup_name, None)

gc.collect()

if device.type == "cuda":
    torch.cuda.empty_cache()

    print(
        "GPU tensor memory: "
        f"{torch.cuda.memory_allocated() / 1024**3:.2f} GiB"
    )

print(
    f"Analysis complete. Results saved in: {out_dir}"
)